stages:
  data_split:
    cmd: python source/data_split.py data/telecom_churn.csv
    deps:
    - source/data_split.py
    params:
    - base.random_state
    - data_source.local_path
    - split.split_ratio
    outs:
    - data/split
  data_processing:
    cmd: python source/data_processing.py data/processed
    deps:
    - data/split
    - source/data_processing.py
    params:
    - process.dir
    - process.test_file
    - process.train_file
    - split.dir
    - split.test_file
    - split.train_file
    outs:
    - data/processed
  train:
    cmd: python source/train.py data/features model/model.pkl
    deps:
    - data/processed
    - source/train.py
    params:
    - base.random_state
    - base.target_col
    - model_dir
    - process.dir
    - process.test_file
    - process.train_file
    - train.params
    outs:
    - model/model.pkl
  evaluate:
    cmd: python source/evaluate.py model/model.pkl data/processed
    deps:
    - data/processed
    - model/model.pkl
    - source/evaluate.py
    outs:
    - eval/importance.png
    - eval/live/plots:
        cache: false
    - eval/prc:
        cache: false
    metrics:
    - eval/live/metrics.json:
        cache: false

plots:
    - ROC:
        template: simple
        x: fpr
        y:
          eval/live/plots/sklearn/roc/train.json: tpr
          eval/live/plots/sklearn/roc/test.json: tpr
    - Confusion-Matrix:
        template: confusion
        x: actual
        y:
          eval/live/plots/sklearn/cm/train.json: predicted
          eval/live/plots/sklearn/cm/test.json: predicted
    - Precision-Recall:
        template: simple
        x: recall
        y:
          eval/prc/train.json: precision
          eval/prc/test.json: precision
    - eval/importance.png  
